### ISSUE TITLE
All fields disappeared from the form builder in 3.6.0 / 3.6.1

### ISSUE THREAD

**Issue by darylknight** [barrelstrength/craft-sprout-forms#377] opened 2019-11-22 09:35 UTC
### Description (screenshots, logs, ...)
I just updated Sprout Forms on a Craft 3 site locally with no issues from 3.5.1 to 3.6.1. When I deployed it to the staging site, all my fields disappeared in the contact form builder. I tried adding them again manually but it said the handle for the field was already taken, so I assume there weren't deleted from the database, but the Forms page in Sprout said there were 0 fields in the form, and none of them showed up on the front end.

### Additional info

- Craft version: 3.3.15
- PHP version: Worked in 7.3.8. The error happened on the staging server which is  7.3.11
- Database driver & version:  MySQL
- Plugins & versions:

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_14d6r)

**Comment by BenParizek** [comment] 2019-11-22 11:44
@darylknight Would you be able to send your database and log files over to sprout@barrelstrengthdesign.com?

**Comment by darylknight** [comment] 2019-11-22 15:03
After discussing with Ben directly I'm going to close this and assume it's site-related rather than a core bug with Sprout Forms. Thanks!

**Comment by riusi88** [comment] 2019-11-22 16:42
I just experienced the a similar issue, with the exception of one of my forms. This all occurred on a local Apache environment after updating Sprout Forms. The form that did not experience the issue was made just yesterday with 3 basic form fields.  

- Craft version: 3.3.15
- PHP version: 7.3.7
- Database driver & version: MySQL
- Sprout Version: Updating from 3.3.9 to 3.6.2

@BenParizek  I can send you a before the error DB, and an after error DB. Let me know if you'd like me to send that your way.

**Comment by BenParizek** [comment] 2019-11-22 18:32
@riusi88 I wasn't able to recreate the issue with Daryl's db. If you could send over your before and after DB's to sprout@barrelstrengthdesign.com it'd be appreciated. It sounds like something may be up but it doesn't seem to happen in all environments so we need more info to narrow it down.

**Comment by siebird** [comment] 2019-11-23 15:29
Hey, Ben. We're having the same issue here. I'll DM the before/after dbs over to you

**Comment by nicholashu** [comment] 2019-11-28 04:05
I am in the same boat

**Comment by TomDeSmet** [comment] 2019-11-29 10:10
Happened here too. Not updating Sprout Forms for now...

**Comment by SamLNL** [comment] 2019-12-02 09:40
Same issue here

**Comment by RyVeata** [comment] 2019-12-02 16:27
Same.  On different server set ups, one being MySQL and others being Postgres.  Happens the moment you upgrade to v3.6.0.

**Comment by natkuu** [comment] 2019-12-02 16:31
I have the same issue upgrading to v3.6.0 on both MySQL and Postgres servers 😑.

**Comment by lesaff** [comment] 2019-12-02 17:19
Same issue here. Updated to latest Sprout Form and all my fields disappeared.

**Comment by BenParizek** [comment] 2019-12-02 18:02
Hi all. I'm working on this issue today.

Right now, the issue appears to be that the Field Layout ID of certain forms is getting reassigned to a new Field Layout ID value (which we need to do to address [another bug](https://github.com/barrelstrength/craft-sprout-forms/issues/360)) but somehow, that migration is getting applied to forms where it shouldn't be getting applied. And we can't seem to figure out what environmental factor some of you have that triggers that logic, but clearly it does.

I'll be running more tests today but so far, while we can see the issue in some upgraded dbs that have been shared with us and that has helped us determine it's a Field Layout issue, we have not been able to recreate the issue in our local environments during a migration. If anybody wants to help take a closer look or offer to join me on a screenshare to debug further, the line in question is [this one](https://github.com/barrelstrength/craft-sprout-forms/blob/v3/src/migrations/m191118_000000_fix_duplicate_forms.php#L51) which appears to be returning true when it shouldn't and my name on Craft Discord is `BenParizek`.

As the issue happens in some environments and not others it appears that some environmental factor is causing that line to return true in some environments. The code in question is trying to dynamically determine the name of a content tables and field columns so perhaps it has something to do with how some of your environments are configured with different defaults that we have on our end. If anybody could share any details about how they have things setup in general.php, db.php, Project Config, or any other environmental considerations that may affect how table names and column handles are defined, that could be helpful. If anything is too sensitive to share here, please drop us a note at sprout@barrelstrengthdesign.com.

**Comment by lesaff** [comment] 2019-12-02 18:27
@BenParizek Thank you for the update. While you are debugging this issue, how do we quickly restore our form(s)? Can we trace the field report ID and change it back to what it was before?

**Comment by BenParizek** [comment] 2019-12-02 18:35
@lesaff I'd recommend rolling back to your previous database if you could as I don't fully understand the issue yet. 

I have not tested the below, and don't know if it would cause new issues or not, but if you wish to be daring and try to solve it in place, as I understand the issue right now, you would probably have to:

- Take a look in your db and find the fields that disappeared in the `craft_fields` table
- Determine the `fieldLayoutId` for those fields
- Manually update the fieldLayoutId in the `craft_sproutforms_forms` table to match the old Field Layout ID

After doing that you'd likely be orphaning the newer, incorrect field layout which probably wouldn't cause any issues but may leave something in the database that isn't accounted by us or anybody else working with field layouts in the future, so a full solution would want to try to review all the field layout sand ensure they have a match and are not orphaned and clean up any that didn't.

**Comment by lesaff** [comment] 2019-12-02 18:40
@BenParizek Thanks for the instructions. That works. I was able to recover my form.

Cheers!

**Comment by BenParizek** [comment] 2019-12-03 00:08
A short update.

We've identified the issue. Some logic in a recent migration doesn't take into account Form Fields that don't have a column in the Form's content table (such as Asset and relations fields). Working on a fix.

**Comment by BenParizek** [comment] 2019-12-03 08:59
Hi Folks. I've just pushed Sprout Forms v3.6.5 that (I hope) will address this issue. 

The **recommended** upgrade path is to revert to your pre-upgrade database and re-run the update to the latest version of Sprout Forms.

If you are in a situation where you can't roll back, you will have to address this issue manually (we are unable to resolve it with migration because we would be guessing at how certain field layouts match up with your forms in the database). I've outlined the steps to address this manually a couple of messages above, and, if you are uncomfortable directly accessing the database like that drop us a note at sprout@barrelstrengthdesign.com and we'll help you through the process.

----

I say "I hope" above because I still haven't been able to recreate the migration problem myself. In reviewing the code and provided databases closely, I did discover a potential issue with our logic and I've refactored the migration causing this issue to do things in a slightly different way which I believe will address the more general problem. So, while I'm confident we fixed at least one issue here, I still can't explain why this seems to happen in some environments and not others as multiple people have described.

Thank you for your patience through this one. If you run into any further issues in the next update, please update this thread and we'll address it.

**Comment by siebird** [comment] 2019-12-03 14:01
Hey @BenParizek. I really appreciate your attention and support on this one. I can only imagine–now get some much need rest 😴

**Comment by riusi88** [comment] 2019-12-03 14:10
@BenParizek thank you for the hard work! I can confirm that updating to v3.6.5 fixed the issue for me. I was fortunate enough to have a backup of my database before the update as well.

**Comment by BenParizek** [comment] 2019-12-03 18:50
It sounds like this is successfully resolving the issue so I'm going to close this out. Please reopen if you run into any additional issues.

For anybody who may be unable to rollback, here are the steps to upgrade manually with a bit more detail. We don't recommend this path as editing the database directly can lead to other issues if you don't make all the relevant, related updates, but the details are here for you to do what you will:

The **sproutforms_forms** table and the **fields** table are linked via the **fields.context** column. Fields for a particular form will have the `context`: **sproutForms:FORMID** (so, if your form is Element ID 123, the context column for that form would read: **sproutForms:123**).

_Note: This troublesome bug originated from a different bug that was introduced a couple of releases ago where duplicating a form did not add the proper `context` for the fields, so, if you duplicated a form recently you may not see the fields for that form appear when searching for them via the `context` like described above. This current migration is finding those duplicated forms with issues and assigning those broken, duplicated forms to a new, empty layout ID to avoid a scenario where deleting the duplicate form or one of its fields could also delete the original form fields._

Once you find the fields that should be associated with your forms, you can note down their IDs (**fields.id**) and determine which Field Layout ID they are associated with in the **fieldlayoutfields** table. In the **fieldlayoutfields** table you should find a group of those fields in question all with the same Layout ID (**fieldlayoutfields.layoutId**). 

Note down that **fieldlayoutfields.layoutId** and update the **sproutforms_forms.layoutId** value to restore the relationship between the fields.

**Closed by BenParizek** 2019-12-03 18:50 UTC
Labels: bug, c3

**Comment by BenParizek** [comment] 2019-12-10 17:37
If anybody else discovers they ran into this issue and can't roll back, I've created the below [Content Migration](https://docs.craftcms.com/v3/extend/migrations.html) that can help with updating the Field Layout IDs of several forms. You will still have to take the time to dig through the database to determine the proper Field Layout IDs for each form, but this can help push those changes to a different environment if you have to deal with a separate release workflow too access production or just have a lot of forms and would prefer a migration:

1. Copy the script below into the folder `/migrations` folder in your project. This folder will be at the same level as your `/vendor` folder and you'll name the file the same as the class name `/migrations/m191212_000000_sproutforms_fieldlayoutid_fix.php`
2. Update the `$formFieldLayoutMap` to reference your existing Form IDs and the proper Field Layout IDs that you identify in the DB
3. Visit the Craft CP `Utilities->Migrations` tab to run your migrations

If you want to test your migration, you can do so in a safe environment. Once you run the migration, there will no longer be an option to run it again. To run it again you will want to re-import your test database or visit the `craft_migrations` table in the database and delete the record that tells Craft that this migration was applied.  When things look good, you can push it to production and run the migration on the production database.

``` php
<?php /** @noinspection ClassConstantCanBeUsedInspection */

namespace craft\contentmigrations;

use craft\db\Migration;

/**
 * m191212_000000_sproutforms_fieldlayoutid_fix migration.
 */
class m191212_000000_sproutforms_fieldlayoutid_fix extends Migration
{
    /**
     * @inheritdoc
     */
    public function safeUp(): bool
    {
        $formFieldLayoutMap = [
            [
                'formId' => 123,
                'fieldLayoutId' => 321
            ],
            [
                'formId' => 456,
                'fieldLayoutId' => 654
            ]
        ];

        foreach ($formFieldLayoutMap as $form) {
            $this->update('{{%sproutforms_forms}}', [
                'fieldLayoutId' => $form['fieldLayoutId']
            ], [
                'id' => $form['formId']
            ], [], false);
        }

        return true;
    }

    /**
     * @inheritdoc
     */
    public function safeDown(): bool
    {
        echo "m191212_000000_sproutforms_fieldlayoutid_fix cannot be reverted.\n";
        return false;
    }
}
```
