### ISSUE TITLE
Craft 2 > 3 Migration error

### ISSUE THREAD

**Issue by engram-design** [barrelstrength/craft-sprout-forms#315] opened 2019-07-17 04:10 UTC
Getting the following migration error:

```

One of Sprout Forms’s migrations failed.

Unknown Property: Setting unknown property: barrelstrength\sproutbaseemail\elements\NotificationEmail::pluginHandle

Migration: barrelstrength\sproutforms\migrations\m180314_161540_craft2_to_craft3

Output:

> add column siteId integer NOT NULL AFTER elementId to table {{%sproutformscontent_contactus}} ... done (time: 0.048s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.002s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.000s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.000s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.000s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.000s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.000s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.024s)
> update in {{%sproutformscontent_contactus}} ... done (time: 0.001s)
> create unique index craft_sproutformscontent_contactus_elementId_siteId_idx on {{%sproutformscontent_contactus}} (elementId,siteId) ... done (time: 0.025s)
> add foreign key craft_sproutformscontent_contactus_siteId_fk: {{%sproutformscontent_contactus}} (siteId) references {{%sites}} (id) ... done (time: 0.044s)
> drop index craft_sproutformscontent_contactus_elementId_locale_unq_idx on {{%sproutformscontent_contactus}} ... done (time: 0.014s)
> drop column locale from table {{%sproutformscontent_contactus}} ... done (time: 0.040s)
> add column siteId integer NOT NULL AFTER elementId to table {{%sproutformscontent_form1}} ... done (time: 0.017s)
> create unique index craft_sproutformscontent_form1_elementId_siteId_idx on {{%sproutformscontent_form1}} (elementId,siteId) ... done (time: 0.011s)
> add foreign key craft_sproutformscontent_form1_siteId_fk: {{%sproutformscontent_form1}} (siteId) references {{%sites}} (id) ... done (time: 0.020s)
> drop index craft_sproutformscontent_form1_elementId_locale_unq_idx on {{%sproutformscontent_form1}} ... done (time: 0.007s)
> drop column locale from table {{%sproutformscontent_form1}} ... done (time: 0.011s)
> drop foreign key craft_sproutformscontent_form1_locale__siteId_fk from table craft_sproutformscontent_form1 ... done (time: 0.010s)
> drop index craft_sproutformscontent_form1_locale__siteId_fk on {{%sproutformscontent_form1}} ... done (time: 0.009s)
> drop column locale__siteId from table {{%sproutformscontent_form1}} ... done (time: 0.012s)
> add column siteId integer NOT NULL AFTER elementId to table {{%sproutformscontent_partybookingform}} ... done (time: 0.038s)
> update in {{%sproutformscontent_partybookingform}} ... done (time: 0.003s)
> update in {{%sproutformscontent_partybookingform}} ... done (time: 0.001s)
> update in {{%sproutformscontent_partybookingform}} ... done (time: 0.001s)
> update in {{%sproutformscontent_partybookingform}} ... done (time: 0.001s)
> update in {{%sproutformscontent_partybookingform}} ... done (time: 0.001s)
> update in {{%sproutformscontent_partybookingform}} ... done (time: 0.001s)
> update in {{%sproutformscontent_partybookingform}} ... done (time: 0.001s)
> update in {{%sproutformscontent_partybookingform}} ... done (time: 0.001s)
> update in {{%sproutformscontent_partybookingform}} ... done (time: 0.001s)
> update in {{%sproutformscontent_partybookingform}} ... done (time: 0.001s)
> update in {{%sproutformscontent_partybookingform}} ... done (time: 0.001s)
> update in {{%sproutformscontent_partybookingform}} ... done (time: 0.001s)
> create unique index craft_sproutformscontent_partybookingform_elementId_siteId_idx on {{%sproutformscontent_partybookingform}} (elementId,siteId) ... done (time: 0.022s)
> add foreign key craft_sproutformscontent_partybookingform_siteId_fk: {{%sproutformscontent_partybookingform}} (siteId) references {{%sites}} (id) ... done (time: 0.039s)
> drop index craft_sproutformsconten_partybookingfor_elementId_locale_unq_idx on {{%sproutformscontent_partybookingform}} ... done (time: 0.013s)
> drop column locale from table {{%sproutformscontent_partybookingform}} ... done (time: 0.036s)
> drop foreign key craft_sproutformscontent_partybookingform_locale__siteId_fk from table craft_sproutformscontent_partybookingform ... done (time: 0.016s)
> drop index craft_sproutformscontent_partybookingform_locale__siteId_fk on {{%sproutformscontent_partybookingform}} ... done (time: 0.011s)
> drop column locale__siteId from table {{%sproutformscontent_partybookingform}} ... done (time: 0.042s)
> drop column enableTemplateOverrides from table {{%sproutforms_forms}} ... done (time: 0.042s)
Exception: Setting unknown property: barrelstrength\sproutbaseemail\elements\NotificationEmail::pluginHandle (/Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Component.php:209)
#0 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/base/Element.php(893): yii\base\Component->__set('pluginHandle', 'sprout-forms')
#1 /Users/joshcrawford/public_html/site/vendor/barrelstrength/sprout-forms/src/migrations/m180314_161540_craft2_to_craft3.php(152): craft\base\Element->__set('pluginHandle', 'sprout-forms')
#2 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/Migration.php(56): barrelstrength\sproutforms\migrations\m180314_161540_craft2_to_craft3->safeUp()
#3 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#4 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(barrelstrength\sproutforms\migrations\m180314_161540_craft2_to_craft3))
#5 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#6 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
#7 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/controllers/UpdaterController.php(208): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#8 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#9 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('migrate', Array)
#12 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#13 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Application.php(298): yii\base\Module->runAction('updater/migrate', Array)
#14 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Application.php(652): craft\web\Application->runAction('updater/migrate')
#15 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Application.php(250): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#16 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /Users/joshcrawford/public_html/site/public_html/index.php(30): yii\base\Application->run()
#18 {main}
```

Looking at the code, it seems an issue with `m180314_161540_craft2_to_craft3:152`, which is:

```
$notificationEmail->pluginHandle = 'sprout-forms';
```

This should maybe be:
```
$notificationEmail->viewContext = 'sprout-forms';
```

Removing this line throws another migration error about a missing `viewContext` attribute, so renaming it works. Not sure if that's correct.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_13dhf)

**Comment by engram-design** [comment] 2019-07-17 04:45
Another error for Sprout Reports, with the same resolution:

```
One of Sprout Reports’s migrations failed.

Database Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pluginHandle' in 'field list'
The SQL being executed was: UPDATE craft_sproutreports_datasources SET pluginHandle='sprout-reports' WHERE id='1'

Migration: barrelstrength\sproutreports\migrations\m190628_000000_fix_data_sources_sproutreports

Output:

> update in {{%sproutreports_datasources}} ...Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pluginHandle' in 'field list'
The SQL being executed was: UPDATE craft_sproutreports_datasources SET pluginHandle='sprout-reports' WHERE id='1' (/Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'UPDATE craft_s...')
#1 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('UPDATE craft_s...')
#2 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/Migration.php(292): yii\db\Command->execute()
#3 /Users/joshcrawford/public_html/site/vendor/barrelstrength/sprout-base-reports/src/migrations/m190628_000000_fix_data_sources.php(62): craft\db\Migration->update('{{%sproutreport...', Array, Array, Array, false)
#4 /Users/joshcrawford/public_html/site/vendor/barrelstrength/sprout-reports/src/migrations/m190628_000000_fix_data_sources_sproutreports.php(22): barrelstrength\sproutbasereports\migrations\m190628_000000_fix_data_sources->safeUp()
#5 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/Migration.php(56): barrelstrength\sproutreports\migrations\m190628_000000_fix_data_sources_sproutreports->safeUp()
#6 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#7 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(barrelstrength\sproutreports\migrations\m190628_000000_fix_data_sources_sproutreports))
#8 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#9 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
#10 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/controllers/UpdaterController.php(208): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#11 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#12 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('migrate', Array)
#15 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#16 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Application.php(298): yii\base\Module->runAction('updater/migrate', Array)
#17 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Application.php(652): craft\web\Application->runAction('updater/migrate')
#18 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Application.php(250): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#19 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /Users/joshcrawford/public_html/site/public_html/index.php(30): yii\base\Application->run()
#21 {main}
```

**Comment by BenParizek** [comment] 2019-07-17 13:29
@engram-design I just pushed a release that I believe will solve this. The issue has to do with us using the Element API in the Craft 2 to Craft 3 migration and then changing the properties on the model in a recent release. I think the longer-term fix will require us to update `minVersionRequired` but I've added back that property for this release.

**Comment by engram-design** [comment] 2019-07-24 12:37
Just got this again:

```
One of Sprout Forms’s migrations failed.

Database Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pluginHandle' in 'field list'
The SQL being executed was: UPDATE sproutreports_datasources SET pluginHandle='sprout-reports' WHERE id='1'

Migration: barrelstrength\sproutforms\migrations\m190628_000000_fix_data_sources_sproutforms

Output:

> update in {{%sproutreports_datasources}} ...Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pluginHandle' in 'field list'
The SQL being executed was: UPDATE sproutreports_datasources SET pluginHandle='sprout-reports' WHERE id='1' (/Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'UPDATE sproutr...')
#1 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('UPDATE sproutr...')
#2 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/Migration.php(292): yii\db\Command->execute()
#3 /Users/joshcrawford/public_html/site/vendor/barrelstrength/sprout-base-reports/src/migrations/m190628_000000_fix_data_sources.php(62): craft\db\Migration->update('{{%sproutreport...', Array, Array, Array, false)
#4 /Users/joshcrawford/public_html/site/vendor/barrelstrength/sprout-forms/src/migrations/m190628_000000_fix_data_sources_sproutforms.php(23): barrelstrength\sproutbasereports\migrations\m190628_000000_fix_data_sources->safeUp()
#5 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/Migration.php(56): barrelstrength\sproutforms\migrations\m190628_000000_fix_data_sources_sproutforms->safeUp()
#6 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#7 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(barrelstrength\sproutforms\migrations\m190628_000000_fix_data_sources_sproutforms))
#8 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#9 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
#10 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/controllers/UpdaterController.php(208): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#11 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#12 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('migrate', Array)
#15 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#16 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('updater/migrate', Array)
#17 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Application.php(653): craft\web\Application->runAction('updater/migrate')
#18 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Application.php(251): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#19 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /Users/joshcrawford/public_html/site/public_html/index.php(29): yii\base\Application->run()
#21 {main}
```

**Comment by andrelopez** [comment] 2019-07-26 20:53
Hi @engram-design 

Could you please update Sprout Forms to v3.3.9 and try the migration again?

Please let us know if is solved

**Comment by riusi88** [comment] 2019-08-13 18:53
Hi @engram-design I'm experiencing the same error. Here is my log and some info regarding my environment. I'd like to prevent re-creating the forms, and dropping all the sprout form db tables at all costs. 

`Unknown Property: Setting unknown property: barrelstrength\sproutbaseemail\records\NotificationEmail::viewContext

Migration: barrelstrength\sproutforms\migrations\m180314_161540_craft2_to_craft3

Output:

> update in {{%sproutformscontent_requestresource}} ... done (time: 0.000s)
> update in {{%sproutformscontent_requestresource}} ... done (time: 0.000s)
> update in {{%sproutformscontent_requestresource}} ... done (time: 0.000s)
> update in {{%sproutformscontent_requestresource}} ... done (time: 0.000s)
> update in {{%sproutformscontent_expertscontactform}} ... done (time: 0.000s)
> update in {{%sproutformscontent_expertscontactform}} ... done (time: 0.000s)
> update in {{%sproutformscontent_expertscontactform}} ... done (time: 0.000s)
> update in {{%sproutformscontent_expertscontactform}} ... done (time: 0.000s)
> update in {{%sproutformscontent_trustedcatalyticconverterrecyclingform}} ... done (time: 0.000s)
> update in {{%sproutformscontent_trustedcatalyticconverterrecyclingform}} ... done (time: 0.000s)
> update in {{%sproutformscontent_trustedcatalyticconverterrecyclingform}} ... done (time: 0.000s)
> update in {{%sproutformscontent_trustedcatalyticconverterrecyclingform}} ... done (time: 0.000s)
> update in {{%sproutformscontent_trustedcatalyticconverterrecyclingform}} ... done (time: 0.000s)
Exception: Setting unknown property: barrelstrength\sproutbaseemail\records\NotificationEmail::viewContext (/Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/yiisoft/yii2/base/Component.php:209)
#0 /Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/yiisoft/yii2/db/BaseActiveRecord.php(324): yii\base\Component->__set('viewContext', 'sprout-forms')
#1 /Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/barrelstrength/sprout-base-email/src/elements/NotificationEmail.php(308): yii\db\BaseActiveRecord->__set('viewContext', 'sprout-forms')
#2 /Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/craftcms/cms/src/services/Elements.php(645): barrelstrength\sproutbaseemail\elements\NotificationEmail->afterSave(true)
#3 /Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/barrelstrength/sprout-base-email/src/services/NotificationEmails.php(59): craft\services\Elements->saveElement(Object(barrelstrength\sproutbaseemail\elements\NotificationEmail), false)
#4 /Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/barrelstrength/sprout-forms/src/migrations/m180314_161540_craft2_to_craft3.php(162): barrelstrength\sproutbaseemail\services\NotificationEmails->saveNotification(Object(barrelstrength\sproutbaseemail\elements\NotificationEmail))
#5 /Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/craftcms/cms/src/db/Migration.php(56): barrelstrength\sproutforms\migrations\m180314_161540_craft2_to_craft3->safeUp()
#6 /Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#7 /Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(barrelstrength\sproutforms\migrations\m180314_161540_craft2_to_craft3))
#8 /Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#9 /Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
#10 /Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/craftcms/cms/src/controllers/UpdaterController.php(208): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#11 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#12 /Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('migrate', Array)
#15 /Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#16 /Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('updater/migrate', Array)
#17 /Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/craftcms/cms/src/web/Application.php(653): craft\web\Application->runAction('updater/migrate')
#18 /Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/craftcms/cms/src/web/Application.php(251): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#19 /Applications/MAMP/htdocs/basf_catalysts/craft3/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /Applications/MAMP/htdocs/basf_catalysts/craft3/web/index.php(42): yii\base\Application->run()
#21 {main}
`

**Migrating from Craft CMS 2.7.10 to Craft 3** 

**In Craft 2 I had installed:**
- Sprout Forms 2.6.4
- Sprout Email 3.1.4
- Sprout Fields 2.2.0

**Trying this on:**
- PHP 7.2.1
- Apache Server

**Comment by BenParizek** [comment] 2019-08-16 16:29
@engram-design @riusi88 This migration is addressed the latest release of Sprout Forms v3.4.0 and Sprout Reports v1.2.6

**Comment by jaydensmith** [comment] 2019-10-30 03:07
This issue is still present
```
    > drop column enableTemplateOverrides from table {{%sproutforms_forms}} ... done (time: 0.023s)
Exception: Setting unknown property: barrelstrength\sproutbaseemail\records\NotificationEmail::viewContext (/Users/jaydensmith/public_html/site/vendor/yiisoft/yii2/base/Component.php:209)
#0 /Users/jaydensmith/public_html/site/vendor/yiisoft/yii2/db/BaseActiveRecord.php(324): yii\base\Component->__set('viewContext', 'sprout-forms')
#1 /Users/jaydensmith/public_html/site/vendor/barrelstrength/sprout-base-email/src/elements/NotificationEmail.php(308): yii\db\BaseActiveRecord->__set('viewContext', 'sprout-forms')
#2 /Users/jaydensmith/public_html/site/vendor/craftcms/cms/src/services/Elements.php(2023): barrelstrength\sproutbaseemail\elements\NotificationEmail->afterSave(true)
#3 /Users/jaydensmith/public_html/site/vendor/craftcms/cms/src/services/Elements.php(525): craft\services\Elements->_saveElementInternal(Object(barrelstrength\sproutbaseemail\elements\NotificationEmail), false, false)
#4 /Users/jaydensmith/public_html/site/vendor/barrelstrength/sprout-base-email/src/services/NotificationEmails.php(59): craft\services\Elements->saveElement(Object(barrelstrength\sproutbaseemail\elements\NotificationEmail), false)
#5 /Users/jaydensmith/public_html/site/vendor/barrelstrength/sprout-forms/src/migrations/m180314_161540_craft2_to_craft3.php(162): barrelstrength\sproutbaseemail\services\NotificationEmails->saveNotification(Object(barrelstrength\sproutbaseemail\elements\NotificationEmail))
#6 /Users/jaydensmith/public_html/site/vendor/craftcms/cms/src/db/Migration.php(58): barrelstrength\sproutforms\migrations\m180314_161540_craft2_to_craft3->safeUp()
#7 /Users/jaydensmith/public_html/site/vendor/craftcms/cms/src/db/MigrationManager.php(239): craft\db\Migration->up(true)
#8 /Users/jaydensmith/public_html/site/vendor/craftcms/cms/src/db/MigrationManager.php(159): craft\db\MigrationManager->migrateUp(Object(barrelstrength\sproutforms\migrations\m180314_161540_craft2_to_craft3))
#9 /Users/jaydensmith/public_html/site/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#10 /Users/jaydensmith/public_html/site/vendor/craftcms/cms/src/console/controllers/MigrateController.php(265): craft\services\Updates->runMigrations(Array)
#11 [internal function]: craft\console\controllers\MigrateController->actionAll()
#12 /Users/jaydensmith/public_html/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /Users/jaydensmith/public_html/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /Users/jaydensmith/public_html/site/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#15 /Users/jaydensmith/public_html/site/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#16 /Users/jaydensmith/public_html/site/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#17 /Users/jaydensmith/public_html/site/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#18 /Users/jaydensmith/public_html/site/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#19 /Users/jaydensmith/public_html/site/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#20 /Users/jaydensmith/public_html/site/craft(22): yii\base\Application->run()
#21 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Sprout Forms.'

in /Users/jaydensmith/public_html/site/vendor/craftcms/cms/src/services/Updates.php:233

Stack trace:
#0 /Users/jaydensmith/public_html/site/vendor/craftcms/cms/src/console/controllers/MigrateController.php(265): craft\services\Updates->runMigrations(Array)
#1 [internal function]: craft\console\controllers\MigrateController->actionAll()
#2 /Users/jaydensmith/public_html/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /Users/jaydensmith/public_html/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /Users/jaydensmith/public_html/site/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#5 /Users/jaydensmith/public_html/site/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#6 /Users/jaydensmith/public_html/site/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#7 /Users/jaydensmith/public_html/site/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#8 /Users/jaydensmith/public_html/site/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#9 /Users/jaydensmith/public_html/site/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#10 /Users/jaydensmith/public_html/site/craft(22): yii\base\Application->run()
#11 {main}
```

**Comment by BenParizek** [comment] 2019-11-14 13:37
@jaydensmith Would you be able to share the database you are seeing this issue on with sprout@barrelstrengthdesign.com? If not the whole database, perhaps just the Sprout tables? This issue is feeling a bit like whack-a-mole and it would be helpful if we could confirm we're on the right track with a fix.

**Comment by BenParizek** [comment] 2019-11-19 21:15
@jaydensmith This should be resolved in the latest release (v3.6.1) now available in the Plugin Store.

**Comment by jaydensmith** [comment] 2019-11-20 04:43
Hey @BenParizek, thanks, the `viewContext` issue is gone, but now the same issue with the `sendRule` column missing.

**Comment by BenParizek** [comment] 2020-02-27 12:50
This is the only instance where this came up. I'm going to close this out and if the issue persists, reach out to sprout@barrelstrengthdesign.com and we'll address it directly. My guess, in this case, is the follow-up issue had to do with the failure caused by the initial issue which was resolved.

**Closed by BenParizek** 2020-02-27 12:50 UTC
Labels: c3, question
