### ISSUE TITLE
Notifications Section in CMS Throws Exception

### ISSUE THREAD

**Issue by mattcdavis1** [barrelstrength/craft-sprout-forms#479] opened 2020-05-17 15:51 UTC
### Description (screenshots, logs, ...)
The notifications controller attempts to call get_class on a string which throws an exception. [Here's a screenshot](https://drive.google.com/file/d/1d4DTMqLBGaAWHzbPuK_R1lt8pRhbUGh8/view?usp=drivesdk).

### Steps to reproduce

1. Navigate to {adminUrl}/admin/sprout-forms/notifications/edit/new
2. See exception

### Additional info

- Craft version: Craft Solo 3.4.19.1
- PHP version: 7.4.4
- Database driver & version:  MySQL 5.7
- Plugins & versions:

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2sa4t)

**Comment by nathannerdymind** [comment] 2020-05-18 19:59
### Description (screenshots, logs, ...)

I am having the same error after updating to version 4.4.2 and installing the plugin on a new site. Can not create new notifications. Default template has been reset to custom template in settings `/admin/sprout-email/settings/notifications`

Craft Error `get_class() expects parameter 1 to be object, string given`
`/vendor/barrelstrength/sprout-base-email/src/controllers/NotificationsController.php`

`#212- // Set a default template if we don't have one set
        if (!$notificationEmail->emailTemplateId) {
            $notificationEmail->emailTemplateId = get_class($defaultEmailTemplateId);
        }`

### Steps to reproduce

- Install plugin.
- Click the "New Notification" button.
OR
- Update plugin to 4.4.2
- Click the "New Notification" button.

### Additional info

- Craft version: 3.4.20
- PHP version: 7.3
- Database driver & version: MySQL 5.7
- Plugins & versions: Sprout Email Lite and Sprout Email Pro

**Comment by BenParizek** [comment] 2020-05-18 21:46
I can recreate. Working on a fix.

**Comment by BenParizek** [comment] 2020-05-18 22:31
@mattcdavis1 @nathannerdymind I've just released Sprout Forms v3.11.7 and Sprout Email v4.4.3 which should resolve this issue.

@nathannerdymind I also tested updating from Sprout Email v4.3.0 to 4.4.2 and the globals settings do retain themselves. We recently had a migration bug that could cause settings to get reset so depending on the timing of your update, you could have run into that. That's fixed now but due to the nature of the bug being in a migration, the only way to get those original settings back would be to go back to the original db you were updating from and re-run the migration.

As this is a different topic than this current ticket which I'll be closing out, please reach out to sprout@barrelstrengthdesign.com if you have any further questions there and we'll help you get things resolved.

**Closed by BenParizek** 2020-05-18 22:31 UTC
