### ISSUE TITLE
Can't install Sprout Forms after upgrade to Craft 3. Database Exception: SQLSTATE[42S22]: error/Couldn’t install plugin

### ISSUE THREAD

**Issue by AnnaZLinka** [barrelstrength/craft-sprout-forms#494] opened 2020-06-03 13:25 UTC
### Description (screenshots, logs, ...)

I'm working with upgrading from Craft 2 to 3 on the project, but get a constant error while trying to install Sprout Form plugin. Havn't got any issues with Sprout Emails and Fields.

### Steps to reproduce
1. Imported db into Craft 3 project, but removed Sprout Forms from composer. Could install all plugins (beside Forms, not even tried) and have project running normally.
2. Tried to install Sprout Forms via composer adding "barrelstrength/sprout-forms": "3.11.5", with composer update.
3. It's not possible - I get error with db: One of Sprout Forms’s migrations failed.

```
Database Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sproutforms_forms.submissionMethod' in 'field list'
The SQL being executed was: SELECT elements.id, elements.fieldLayoutId, elements.uid, elements.enabled, elements.archived, elements.dateCreated, elements.dateUpdated, elements_sites.slug, elements_sites.siteId, elements_sites.uri, elements_sites.enabled AS enabledForSite, sproutforms_forms.groupId, sproutforms_forms.id, sproutforms_forms.fieldLayoutId, sproutforms_forms.name, sproutforms_forms.handle, sproutforms_forms.titleFormat, sproutforms_forms.displaySectionTitles, sproutforms_forms.redirectUri, sproutforms_forms.saveData, sproutforms_forms.submissionMethod, sproutforms_forms.errorDisplayMethod, sproutforms_forms.successMessage, sproutforms_forms.errorMessage, sproutforms_forms.submitButtonText, sproutforms_forms.formTemplateId, sproutforms_forms.enableCaptchas
FROM (SELECT elements.id AS elementsId, elements_sites.id AS elementsSitesId
FROM craft_elements elements
INNER JOIN craft_sproutforms_forms sproutforms_forms ON sproutforms_forms.id = elements.id
INNER JOIN craft_elements_sites elements_sites ON elements_sites.elementId = elements.id
WHERE (elements.id=50262) AND (elements.archived=FALSE) AND (elements.dateDeleted IS NULL) AND (elements_sites.enabled=TRUE) AND (elements.draftId IS NULL) AND (elements.revisionId IS NULL)
ORDER BY sproutforms_forms.name
LIMIT 1) subquery
INNER JOIN craft_sproutforms_forms sproutforms_forms ON sproutforms_forms.id = subquery.elementsId
INNER JOIN craft_elements elements ON elements.id = subquery.elementsId
INNER JOIN craft_elements_sites elements_sites ON elements_sites.id = subquery.elementsSitesId
ORDER BY sproutforms_forms.name
LIMIT 1

Migration: barrelstrength\sproutforms\migrations\m190410_000000_add_payload_forwarding_to_integration

Output:

Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sproutforms_forms.submissionMethod' in 'field list'
The SQL being executed was: SELECT elements.id, elements.fieldLayoutId, elements.uid, elements.enabled, elements.archived, elements.dateCreated, elements.dateUpdated, elements_sites.slug, elements_sites.siteId, elements_sites.uri, elements_sites.enabled AS enabledForSite, sproutforms_forms.groupId, sproutforms_forms.id, sproutforms_forms.fieldLayoutId, sproutforms_forms.name, sproutforms_forms.handle, sproutforms_forms.titleFormat, sproutforms_forms.displaySectionTitles, sproutforms_forms.redirectUri, sproutforms_forms.saveData, sproutforms_forms.submissionMethod, sproutforms_forms.errorDisplayMethod, sproutforms_forms.successMessage, sproutforms_forms.errorMessage, sproutforms_forms.submitButtonText, sproutforms_forms.formTemplateId, sproutforms_forms.enableCaptchas
FROM (SELECT elements.id AS elementsId, elements_sites.id AS elementsSitesId
FROM craft_elements elements
INNER JOIN craft_sproutforms_forms sproutforms_forms ON sproutforms_forms.id = elements.id
INNER JOIN craft_elements_sites elements_sites ON elements_sites.elementId = elements.id
WHERE (elements.id=50262) AND (elements.archived=FALSE) AND (elements.dateDeleted IS NULL) AND (elements_sites.enabled=TRUE) AND (elements.draftId IS NULL) AND (elements.revisionId IS NULL)
ORDER BY sproutforms_forms.name
LIMIT 1) subquery
INNER JOIN craft_sproutforms_forms sproutforms_forms ON sproutforms_forms.id = subquery.elementsId
INNER JOIN craft_elements elements ON elements.id = subquery.elementsId
INNER JOIN craft_elements_sites elements_sites ON elements_sites.id = subquery.elementsSitesId
ORDER BY sproutforms_forms.name
LIMIT 1 (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'SELECT element...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1159): yii\db\Command->internalExecute('SELECT element...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(415): yii\db\Command->queryInternal('fetch', NULL)
#3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(285): yii\db\Command->queryOne()
#4 /var/www/html/vendor/craftcms/cms/src/db/Query.php(168): yii\db\Query->one(NULL)
#5 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1486): craft\db\Query->one(NULL)
#6 /var/www/html/vendor/barrelstrength/sprout-forms/src/services/Forms.php(314): craft\elements\db\ElementQuery->one()
#7 /var/www/html/vendor/barrelstrength/sprout-forms/src/base/Integration.php(71): barrelstrength\sproutforms\services\Forms->getFormById(50262)
#8 /var/www/html/vendor/barrelstrength/sprout-forms/src/base/Integration.php(216): barrelstrength\sproutforms\base\Integration->getForm()
#9 /var/www/html/vendor/barrelstrength/sprout-forms/src/migrations/m190410_000000_add_payload_forwarding_to_integration.php(59): barrelstrength\sproutforms\base\Integration->getSourceFormFieldsAsMappingOptions()
#10 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(52): barrelstrength\sproutforms\migrations\m190410_000000_add_payload_forwarding_to_integration->safeUp()
#11 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#12 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(barrelstrength\sproutforms\migrations\m190410_000000_add_payload_forwarding_to_integration))
#13 /var/www/html/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#14 /var/www/html/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations(Array)
#15 /var/www/html/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#16 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#17 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#19 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('migrate', Array)
#20 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#21 /var/www/html/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('updater/migrate', Array)
#22 /var/www/html/vendor/craftcms/cms/src/web/Application.php(646): craft\web\Application->runAction('updater/migrate')
#23 /var/www/html/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#24 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#25 /var/www/html/public/index.php(21): yii\base\Application->run()
#26 {main}
```
After that it's impossible to do anything. So I tried another approach:
1a. Delete Forms plugin from composer.json, and remove completely composer.lock. Run composer update.
2a. Try to install Sprout Forms via Plugin store. Got the same error as previously:
`Database Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sproutforms_forms.submissionMethod' in 'field list'`

So tried another the last solution:
1b. Delete Sprout Forms plugin from db, which let me continue working with project.
2b. After delete from db I install plugin via Store, and have it visible in Plugins in CP. But when trying to install in Plugins I get  `Couldn’t install plugin."  error.` 

### Additional info

- Craft version: Craft Pro 3.4.19
- PHP version: 7.2.21
- Database driver & version: MySQL 5.7.26
- Plugins & versions: 
      Sprout Email 4.4.6
      Sprout Fields 3.8.3
      "barrelstrength/sprout-forms": "3.12.2",

Files sent:
- `composer.json`
- `storage/logs/web.log`
- database 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2u39p)

**Comment by BenParizek** [comment] 2020-06-05 03:18
@AnnaZLinka I see the initial issue here. It's a bug in a migration and, right now, I believe the best way to get around it will be to initially upgrade to Sprout Forms v3.8.8 to ensure the migration throwing the error runs correctly, and then upgrade the rest of the way after that.

v3.8.8 is just before the bug gets introduced in v3.9.0 and is compatible with Craft 3.4 so you should be able to update to it with your latest codebase. 

_Just to note it here, the migration throwing the error is in Sprout Forms v3.1.0, so if the above stepping stone doesn't work, we may have to consider upgrading to that earlier version first but that would require an earlier version of Craft too so lets' try to avoid that for now. The issues is caused by a call to the service layer in one of the migrations that calls `getForm()` and the data model for forms changes in v3.9.0_

Let me know if updating to v3.8.8 first helps you get around the bug.

**Comment by AnnaZLinka** [comment] 2020-06-11 07:36
Hi @BenParizek. Thank you for the advice. I got to install Forms 3.8.8 on Monday, but somehow.. destroyed it on Tuesday. 
On Tuesday I started with downloading current db from Craft 2 customer. Got it running without Forms installed. Then tried install via CP. No loc though. 
Tried also removing plugin from composer.json (+delete composer.lock) and run again. Gave a try with version 3.1.0. Right now I get constant error with `Trait 'barrelstrength\sproutbase\base\BaseSproutTrait' not found`

<img width="664" alt="Screenshot 2020-06-11 at 08 26 20" src="https://user-images.githubusercontent.com/52034653/84357615-418f3500-abc6-11ea-80a8-ad77c284312a.png">

Since Tuesday (including) I can´t get project with Forms installed running. My guess was it could be the order in which I install other plugins in CP, but last tries were without other plugins, to avoid possible cross-problems. 
Do you have any other ideas how to overcome it?

**Comment by AnnaZLinka** [comment] 2020-06-25 13:47
Hi @BenParizek, do you have any advice? Still stuck with Sprout Forms and upgrade :(

**Comment by BenParizek** [comment] 2020-06-25 14:39
@AnnaZLinka The last error posted there is also indicating that whatever version of Sprout Forms you are targeting is pulling in dependencies of packages that are released after that version and expect the code base to be different. The issue here is not in the code but in the targeted packages by composer and the only way to get around this will probably be to target the specific packages relating to whatever version you are trying to update to.

For example, if you are targeting Sprout Forms v3.1.0, you may also want to add to your composer the specific versions of all the dependencies Sprout Forms used at that version. You can see which versions those were in the composer.json file:
https://github.com/barrelstrength/craft-sprout-forms/blob/v3.1.0/composer.json

``` 
"barrelstrength/sprout-base": "^5.0.1",
"barrelstrength/sprout-base-email": "^1.1.0",
"barrelstrength/sprout-base-fields": "^1.0.7",
"barrelstrength/sprout-base-reports": "^1.0.7",
"barrelstrength/sprout-base-import": "^1.0.4"
```

And you'll want to remove the `^` which triggers the behavior to pull in later versions of the dependencies that may not be compatible with the current version.

``` 
"barrelstrength/sprout-base": "5.0.1",
"barrelstrength/sprout-base-email": "1.1.0",
"barrelstrength/sprout-base-fields": "1.0.7",
"barrelstrength/sprout-base-reports": "1.0.7",
"barrelstrength/sprout-base-import": "1.0.4"
```

Once you get things sorted out, you'll want to remove those from the composer.json file again, as those packages should be managed by the plugin, but in this case, to get around the issue your experiencing this step might need to be taken to ensure the right versions get installed at your interim step.

If you continue to run into issues, maybe we can arrange a screen share to work through it. You can find me on Craft Discord as @BenParizek or drop me a note at our support email and we can sort out a time sprout@barrelstrengthdesign.com

**Comment by BenParizek** [comment] 2020-12-01 19:54
@AnnaZLinka I've tracked down what is going on here and will have a fix for this migration in our next release. I'm still working through several items so can't promise a date on that at the moment.

The issues is in how we handle the Payload Forwarding 'Submit Action' setting during the migration and generate a new Custom Endpoint Integration (which is the new way we handle that in Craft 3)

If you'd like to move forward with a workaround, you can remove the "Submit Action" setting from any forms you have using Payoload Forwarding on Craft 2 (and just resave the form so that value is empty) and then re-add that value by setting up a Custom Endpoint Integration for the forms that you want to forward to a different endpoint on Craft 3.

I'll update this ticket again once we get that release out.

**Comment by AnnaZLinka** [comment] 2020-12-02 12:26
Hey @BenParizek. Glad that you are going further with fixing it! 💪 I had to get around with the forms since it took quite a lot of time, so used another form plugin instead. So that particular project won't need a quick fix now. Although we still have some projects on Craft 2, not in upgrading process there yet, so please keep me inform when the fix is released.

**Comment by BenParizek** [comment] 2021-02-11 02:04
This should be addressed in the latest release of Sprout Forms. 

I'm catching up on several support tickets right now and working on a large update to improve the migration process that has been causing a lot of issues like this. There will likely be several smaller updates coming out over the next couple of weeks so, if possible, I'd recommend holding off on updating until we get Sprout Forms v4.0 out the door which should get things into a lot better shape.

**Closed by BenParizek** 2021-02-11 02:04 UTC
Labels: bug, c3
