### ISSUE TITLE
Could not find package at any version for your minimum-stability

### ISSUE THREAD

**Issue by sjenset** [barrelstrength/craft-sprout-forms#176] opened 2018-10-29 15:15 UTC
### Description

The plugin will not install

### Steps to reproduce

1. cd /path/to/project
2. composer require barrelstrength/sprout-forms
3. See error:

  [InvalidArgumentException]
  Could not find package barrelstrength/sprout-forms at any version for your
  minimum-stability (stable). Check the package spelling or your minimum-stability

### Additional info

- Craft version: 3.0.28
- PHP version: 7.0.24
- Database driver & version: mariadb  5.5.52
- Plugins & versions: Several, although I doubt they would cause this

**Comment by andrelopez** [comment] 2018-10-29 20:47
Hi @sjenset 

this issue is a duplicate of #167

This error is due to Sprout Forms is still in Beta. Run the next command instead:

`composer require barrelstrength/sprout-forms "^3.0.0-beta.26"`

**Closed by andrelopez** 2018-10-29 20:47 UTC
Labels: c3, duplicate, question
