### ISSUE TITLE
Spam entries still send off the notifications

### ISSUE THREAD

**Issue by wei2go** [barrelstrength/craft-sprout-forms#398] opened 2020-01-10 01:08 UTC
### Description
The email notifications are still sent out even if Sprout Forms detects the submission as a Spam. No matter the setting "Sprout Forms -> Settings -> Save Spam to the database" is on or off, the email notification should not be sent off if it is a spam.

It's related to my comment in this post to some extent: https://github.com/barrelstrength/craft-sprout-forms/issues/396#issuecomment-572822617

### Steps to reproduce

1. Sprout Forms -> Settings -> Save Spam to the database is enabled.
2. Notification Settings:
Event: when a form entry is saved.
When entry is created: ticked
Send Rule: Always
3. The spam entries are saved correctly, and the email notifications are also sent.

### Additional info

- Craft version: Craft Pro 3.3.16.3
- PHP version: 7.3.12
- Database driver & version:  MySQL 8.0.18
- Plugins & versions:
Sprout Forms 3.6.4
Sprout Reports 1.2.11
Sprout Fields 3.4.4

**Comment by BenParizek** [comment] 2020-01-10 02:43
@wei2go I've got it on our list to add this as another option in the Send Rule dropdown. For now, you can manually update that send rule if you want to only trigger emails for form submissions that are not spam. You can find an example here: https://github.com/barrelstrength/craft-sprout-forms/issues/385

I'm going to close this out as a duplicate of the above issue.

**Closed by BenParizek** 2020-01-10 02:43 UTC
Labels: duplicate
