### ISSUE TITLE
Notification doesn't send an email

### ISSUE THREAD

**Issue by jeffreyschmitz87** [barrelstrength/craft-sprout-forms#338] opened 2019-09-07 13:45 UTC
### Description (screenshots, logs, ...)

I've updated Sprout Forms from version 3.3.9 to 3.4.0 and sending a notification when a new Sprout Entry is made stopped working. Sending a test e-mail does work but receiving an email from the notification doesn't.

### Steps to reproduce

1. Create a Form
2. Create a Notification with the following settings: 
Event: When a form entry is saved
Check the box: When entry is created?
Check the box where your form is
3. Submit the form

### Additional info

I've configured the `config/app.php` with a custom `mailer` component for sending mails via SMTP with the code below. I'm doing this because I'm running a multisite and each site has it's own mailer settings.
```
'components' => [
        'mailer' => function() {
            // Get the stored email settings
            $settings = craft\helpers\App::mailSettings();

            // Override the transport adapter settings
            $settings->transportType = Smtp::class;
            $settings->fromEmail = EnvironmentLoader::getEmailSetting(EnvironmentLoader::SITE_CONFIG_MAIL_USER);
            $settings->fromName = EnvironmentLoader::getEmailSetting(EnvironmentLoader::SITE_CONFIG_MAIL_NAME);
            $settings->transportSettings = EnvironmentLoader::getEmailSettings();

            // Create a Mailer component config with these settings
            $config = craft\helpers\App::mailerConfig($settings);

            // Instantiate and return it
            return Craft::createObject($config);
        },
    ],
```

I've debugged a bit around between v3.3.9 and v3.4.0 and this function doesn't get called in v3.4.0 https://github.com/barrelstrength/craft-sprout-base-email/blob/v1/src/services/NotificationEmailEvents.php#L166

- Craft version: Craft Pro 3.3.1.1
- PHP version: 7.2.16
- Database driver & version:  MySQL 5.5.5
- Plugins & versions:

Advanced Url Field | 1.0.0
Asset Rev | 6.0.2
Control Panel CSS | 2.2.0
Neo | 2.4.5
Redactor  | 2.3.3.2
SEOmatic | 3.2.23
Sprout Forms | 3.4.0
Super Table | 2.2.1

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_wcxv)

**Comment by BrandonJamesBorders** [comment] 2019-09-11 13:31
@BenParizek Having this issue as well!

Test email sends, notification email does not. No custom Mailer config, just using the Email Settings page in Craft.

**Comment by BrandonJamesBorders** [comment] 2019-09-11 13:39
#330

**Comment by jaydensmith** [comment] 2019-09-11 22:51
@BrandonJamesBorders my most recent issue was the send rule column in the DB having an empty value, I just updated it with an asterisk.

**Comment by BrandonJamesBorders** [comment] 2019-09-13 13:03
@jeffreyschmitz87 Same here. 

@BenParizek  I think you have a bigger problem on your hands here. I'd be glad to provide a copy of website and database for you to test with. For now, we had to switch to FreeForm.

**Comment by BenParizek** [comment] 2019-09-16 22:28
@jeffreyschmitz87 @BrandonJamesBorders I trust something is up with your configurations however we're still unable to recreate this issue.

We recently added the Send Rule feature which can conditionally determine if an email is sent or not. It sounds like you are confirming that the database settings for that are correct and should be evaluating to true.

@jeffreyschmitz87 We took a look at the db you sent over and were able to send emails successfully after we updated the Craft Email settings to our test credentials (and we didn't change any other settings).

Would either of you be available to arrange a hangout to review your particular situations? My schedule is a bit tough this week as I'll be up in Montreal at Dot All but if you happen to be at the conference or want to ping me on Craft Discord (@BenParizek), perhaps we can find a time to connect and dig deeper.

**Comment by jeffreyschmitz87** [comment] 2019-09-17 05:25
@BenParizek I've received a test e-mail from Craft. Was this the only email you've sent? As mentioned above sending test e-mails works. Having a notification which should send an email after a form entry is saved doesn't work.

**Comment by BrandonJamesBorders** [comment] 2019-09-18 15:08
@BenParizek @jeffreyschmitz87 If you end up needing another datapoint after your hangout let me know!

**Comment by jeffreyschmitz87** [comment] 2019-09-25 13:40
@BrandonJamesBorders I think I've found the problem. I did some research and the Javascript Captcha  Spam Protection seems to be the problem in version 3.4.2.

It seems the code it renders is missing a `<script>` tag which turns into failing the spam protection validation (which also fails an event) and faking the submission.

When I disable the Javascript Captcha Spam Protection everything is working.

I've also messaged @BenParizek about this.

**Comment by BrandonJamesBorders** [comment] 2019-09-26 12:59
@jeffreyschmitz87 Ah, good investigation!

**Comment by jeffreyschmitz87** [comment] 2019-10-01 07:02
@BrandonJamesBorders a quick update on this. After some messages with @BenParizek this is what I've come up with:
1) The `<script>` tag does get rendered but it's moved towards the end of page source
2) After some tests it seems using `{% if block('something') %}` (between the code that is used to render the form) is causing the Javascript to render two alojs checks but there's only one form on the page:

```
<script>document.getElementById("alojs5d92f92b1192d6.38545691").value = "alojs5d92f92b1192d6.38545691";
document.getElementById("alojs5d92f92b230848.03505238").value = "alojs5d92f92b230848.03505238";</script>
```

When I disable the `{% if block('something') %}` I don't have a Javascript error anymore and I do get a notification.

Can you confirm that you're also using this `{% if block('something') %}` code in your Twig between your form rendering @BrandonJamesBorders?

**Comment by BenParizek** [comment] 2019-10-02 11:49
I'm going to close this out for now, please re-open or post a new issue if this continues. 

It appears in @jeffreyschmitz87 case the issue was caused by the use of the `block()` function in an if statement. This Twig function rendered the form template a second time during the page load and since the form templates use the `{% js %}` tag, the javascript captcha was being triggered twice on the page. Updating the if statement to use a different method gets the javascript errors resolved and the email sending again.

@BrandonJamesBorders As you've moved on to another solution for now, we can revisit this if you run into it again in the future. As we don't have any other users reporting this issue and have not been able to recreate it, I expect the scenario may be caused by something that we'll need to troubleshoot in your specific environment.

For anybody else that runs into similar issues, when it's not clear if there may be a bug, a good first step is to create a blank template and output the form in question with the default `craft.sproutForms.displayForm('yourForm')` tag. If a default, vanilla form is working is expected, you can re-introduce the customization and complexity step by step and help determine where the issue may be introduced for further troubleshooting.

**Closed by BenParizek** 2019-10-02 11:49 UTC
Labels: bug, c3, need more info

**Comment by BrandonJamesBorders** [comment] 2019-10-02 14:00
@jeffreyschmitz87 @BenParizek 

My ``displayForm`` call was inside a `block.type` switch statement.
